# Основные правила - более мягкие настройки
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - shorthand_operator
  - opening_brace
  - cyclomatic_complexity
  - large_tuple
  - implicit_optional_initialization
  - function_parameter_count
  - closure_parameter_position
  - type_name
  - multiple_closures_with_trailing_closure
  - redundant_void_return
  - leading_whitespace
  - for_where
  - legacy_constructor
  - unused_optional_binding
  - unused_enumerated
  - unneeded_synthesized_initializer
  - nesting
  - unneeded_override
  - statement_position
  - is_disjoint
  - void_function_in_ternary
  - static_over_final_class
  - orphaned_doc_comment
  - computed_accessors_order
  - compiler_protocol_init
  - comment_spacing
  - comma
  - todo
  - force_unwrapping
  - force_try
  - force_cast
  - attribute_name_spacing

# Исключения для определенных файлов
excluded:
  - Pods
  - Dependencies
  - BuildTools
  - fastlane
  - scripts
  - patch
  - Templates
  - ".build"
  - ".swiftpm"
  - "FreeAPS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
  - "build"
  - "SourcePackages"
  - "DerivedData"
  - "*/SourcePackages/*"
  - "*/build/*"
  - "FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift"
